name: password_generator
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.9
  provider: ^3.0.0
  toast: ^0.1.5

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any


flutter:  
  uses-material-design: true
